/*
 * Copyright (c) Microsoft Corporation. All rights reserved. Licensed under the MIT license.
 * See LICENSE in the project root for license information.
 */

/* global console, document, Excel, Office */
const groqModule = require('@langchain/groq');
import { system_prompt } from './prompts.js';
console.log(groqModule);
console.log("Loading taskpane.js...");

function showLoader() {
  document.getElementById('loader').style.display = 'block';
}

function hideLoader() {
  document.getElementById('loader').style.display = 'none';
}

let chat_json = {"chat_history": []};

Office.onReady((info) => {
  if (info.host === Office.HostType.Excel) {
    document.getElementById("sideload-msg").style.display = "none";
    document.getElementById("app-body").style.display = "flex";
    document.getElementById("run").onclick = run;
  }
});

export async function run() {
  showLoader();

  const userInput_ = String(document.getElementById("userInput").value);
  console.log("input value:", userInput_);
  try {
    chat_json = await addChatHistoryEntry(chat_json, "user", userInput_);
    } catch (error) {
    console.error("Error adding user input to chat history:", error);
    }

    let numberOfattemps = 0;
    const maxAttempts = 2;
    let executedResonposeSucessfully = false;

    while ((numberOfattemps < maxAttempts) && 
    (!executedResonposeSucessfully)){
      numberOfattemps+=1;
      
      if (typeof system_prompt !== "string") {
      console.log("system_prompt is not a string:", system_prompt);}

      if (typeof userInput_ !== "string") {
      console.log("system_prompt is not a string:", userInput_);}

      const llm = new groqModule.ChatGroq({
      model: "llama-3.1-8b-instant", // or any other supported model
      temperature: 0.7,
      apiKey:'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' // or pass directly as a string
      });

      const response = await llm.invoke([
        { role: "system", content: system_prompt },
        { role: "user", content: chat_json.chat_history.map(entry => `${entry.role}: ${entry.response}`).join("\n") },
      ]);

      if (response){
        // let code = response.content.replace(/```javascript|```/g, '').trim();
        let code = `function llm_action(context){
                    const worksheet = context.workbook.worksheets.getActiveWorksheet();
                    const range = worksheet.getRange("B1:B5");
                    const formula = "=SUM(B1:B5)";
                    worksheet.getRange("B6").formula = formula;

                    // console.log("Inside llm_action generated by llm");
                    // const sheet = context.workbook.worksheets.getActiveWorksheet();
                    // ABD();
                    // const columnA = sheet.getRange("A:A");
                    // columnA.format.fill.color = "red";
                    context.sync();
                  }`;
        code = `return async function() {
                await Excel.run(async (context) => {
                  const sheet = context.workbook.worksheets.getActiveWorksheet();
                  ABD();
                  const columnA = sheet.getRange("A:A");
                  columnA.format.fill.color = "red";
                  await context.sync();
                });
              };`
        console.log("Generated code:", code);
        chat_json = await addChatHistoryEntry(chat_json, "llm", code);

        const createFn = new Function(code);
        const llm_action = createFn();
      
        try {
          await llm_action(); 
          executedResonposeSucessfully = true;
        }
        catch (error) {
          console.log("Error in dynamic function: " + error);
          chat_json = addChatHistoryEntry(chat_json, "user", "encountering following error while executing your suggested code:" + error.message);
        }

        // try {
        //   await Excel.run(async (context) => {
        //   console.log("Inside Excel.run in taskpane.js");
        //   const script = document.createElement("script");
        //   script.type = "text/javascript";
        //   script.textContent = code
        //   document.head.appendChild(script);
          
        //   try {
        //     llm_action(context);
        //     context.sync();
        //     executedResonposeSucessfully = true;
        //     } 
        //   catch (error) {
        //     console.error("Error in llm_action:", error);
        //     chat_json = addChatHistoryEntry(chat_json, "user", "encountering following error while executing your suggested code:" + error.message);
            
        //   }
        //   await context.sync(); 
        //   console.log("Excel context synced.");
        //   });
        // }
        // catch (error){
        //   console.error("Error in trying to run the generated code from llm:", error);
        // }
      }
      else{
        console.error("Error from API:", response.statusText);
      }
    }

  hideLoader();
  location.reload();
}

function addChatHistoryEntry(chat_json, role, response) {
  chat_json.chat_history.push({
    id: chat_json.chat_history.length + 1,
    timestamp: new Date().toISOString(),
    role: role,
    response: response
  });
  return chat_json;
}